- name: Prereqs
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Check if Incus is installed
      command: rpm -q incus
      register: incus_check
      ignore_errors: yes

    - name: Fail if Incus is not installed
      fail:
        msg: "Required package 'Incus' is not installed"
      when: incus_check.rc != 0

- name: Incus profile
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if profile already exists
      command: incus profile show k3s
      register: k3s_check
      failed_when: false
      changed_when: false

    - name: Create an Incus profile
      ansible.builtin.shell: incus profile create k3s < profile.yaml
      when: k3s_check.rc != 0

- name: Setup Incus containers
  hosts: localhost
  gather_facts: false

  vars:
    container_names:
      - alpha
      - beta
      - gamma

  tasks:
    - name: Check if container {{ item }} exists
      ansible.builtin.shell: |
        incus info {{ item }}
      loop: "{{ container_names }}"
      register: container_check
      failed_when: false
      changed_when: false

    - name: Create container if it doesn't exist
      ansible.builtin.shell: |
        incus launch images:ubuntu/24.04 {{ item.item }} \
        --profile default --profile k3s
      loop: "{{ container_check.results }}"
      when: item.rc != 0
      changed_when: true

- name: Setup Tailscale
  hosts: localhost
  gather_facts: false

  vars:
    container_names:
      - alpha
      - beta
      - gamma

  tasks:
    - name: Get tailscale status
      ansible.builtin.command: tailscale status
      register: tailscale_status
      changed_when: false

    - name: Setup tailscale
      ansible.builtin.shell: |
        incus exec {{ item }} -- sh -c "
          apt update && apt install curl -y &&
          curl -fsSL https://tailscale.com/install.sh | sh
        "
      loop: "{{ container_names }}"
      when: item not in tailscale_status.stdout
      changed_when: true

    - name: Add to tailnet
      ansible.builtin.shell: |
        incus exec {{ item }} -- sh -c "
          tailscale up --authkey {{ tailscale_authkey }} &&
          tailscale set --ssh
        "
      loop: "{{ container_names }}"
      when: item not in tailscale_status.stdout
      changed_when: true
